### ISSUE TITLE
difficulty to understand sbatch_cluster.py

### ISSUE THREAD

**Issue by raveancic** [crazyhottommy/pyflow-cellranger#1]
Dear Tommy,

thank you very much for your contribution in the field of the scRNA, I find really great that you freely share all these stuff to the community.

I am a newbie on both scRNA and snakemake but I have a hunger for learning, I realized a pipeline similar to yours to run snakemake with cellranger count and I was about to submit it to the cluster when I encountered your [sbatch_cluster.py](https://github.com/crazyhottommy/pyflow-cellranger/blob/master/sbatch_cluster.py). It is a couple of days that I am struggling in understanding the utility and difference of this wrapper compared to the --cluster "qsub " modality which in your script is in [pyflow-cellranger.sh](https://github.com/crazyhottommy/pyflow-cellranger/blob/master/pyflow-cellranger.sh). 
I would be very grateful if you could explain this to me because I am not finding a lot of documentation, neither in the manual of snakemake. 

All the best,
Ale

**Comment by crazyhottommy** [comment]
Hi @raveancic,
the `sbatch_cluster.py` is used for more control of the jobs. 
read this https://groups.google.com/forum/#!topic/snakemake/1QelazgzilY. I learned from there.
use 
https://github.com/crazyhottommy/pyflow-cellranger/blob/master/pyflow-cellranger.sh  it is relatively easier.
